name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: rakez

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Set environment variables
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.RAKEZENV }}" > .env

      - name: Start Docker containers
        run: docker compose up --build -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to initialize..."
          sleep 20
          docker compose ps

      - name: Backup PostgreSQL before migration
        run: |
          mkdir -p db_backups
          docker exec postgres-db-game pg_dump -U postgres -d game > db_backups/backup.sql

      - name: Upload DB backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: postgres-backup
          path: db_backups/backup.sql

      - name: Run Prisma migrations
        run: docker compose exec -T app npx prisma migrate deploy

      - name: Stop containers
        run: docker compose down
