name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: rakez  # ✅ Fixed runner

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file
        env:
          RAKEZENV: ${{ secrets.RAKEZENV }}
        run: echo "$RAKEZENV" > .env  # ✅ Better secret handling

      - name: Install dependencies via Docker Compose
        run: docker compose up --build --exit-code-from app  # ✅ Exit on failure
