name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Set environment variables
        run: echo "HOME=/root" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file
        run: |
          touch .env
          echo "${{ secrets.RAKEZENV }}" > .env

      - name: Remove old app container (only if exists)
        run: |
          docker rm -f nest-app-game || true

      - name: Rebuild and start containers
        run: docker-compose up --build -d
